# development options
livereload: true
port: 8000

disable_disk_cache: true
strict_front_matter: true

sass:
  load_paths:
    - _src/dependencies/katsute/css
    - _src/dependencies/node/bootstrap/scss
    - _src/dependencies/node/fontawesome/scss
  style: compressed

collections:
  src:
    output: true
    permalink: /:path:output_ext

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - CNAME
  - _config.yml
  - LICENSE
  - README.md
  - '*.json'
  - '*.ts'
  - _src/dependencies/node/bootstrap/scss
  - _src/dependencies/node/fontawesome/scss

# github plugins
plugins:
  - jekyll-optional-front-matter
  - jekyll-readme-index

readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: true

# third-party
compress_html:
  clippings: all
  comments: all
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

# variables
url: https://katsute.dev